### ISSUE TITLE
The user should see the Sign In button while entering the password

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#22]
Device: iPhone 8

Steps to reproduce:
1. Go to the App
2. Enter password

Actual result:
On the device, the red frame covers the application area, Sign In button is not visible
![IMG_3327](https://user-images.githubusercontent.com/13810654/148728048-61ffeac0-bd5e-424d-b0b0-c48fb30412e4.png)

**Comment by jnorbert** [comment]
Unfortunately, even the field for entering the password is now hidden
![IMG_3381](https://user-images.githubusercontent.com/13810654/150519349-46d3c49c-6905-492d-bd51-46d900548fa9.JPG)

**Comment by JeneaVranceanu** [comment]
@jnorbert Thanks for reporting! What is the iOS version on your device?

We did test that bug fix on iPhone 7 (real device) and iPhone 12 mini (simulator). I'll make sure it is tested on iPhone 8 just in case there is an edge case.

**Comment by jnorbert** [comment]
@JeneaVranceanu I have iPhone 8 with the iOS 15.1

**Comment by arturtkachenko** [comment]
@jnorbert We removed Sign In option so this issue is not actual anymore and I'm closing it. Regarding other keyboard overlapping issues, I'll on that today.
