### ISSUE TITLE
Application is crashing after editing the profile

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#32]
iOS: 15.1
iPhone 8

Steps to reproduce:
1. Log in to your profile
2. Go to the settings
3. Enter the username
4. Save

Actual result:
[Recording](https://user-images.githubusercontent.com/13810654/149469408-149d1358-27d4-4af3-9f61-15b6d79918fd.mov)

**Comment by arturtkachenko** [comment]
Fixed in 0.1 (16) - TestFlight.
