### ISSUE TITLE
Part of the data is not saved when creating a profile

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#33]
iOS: 15.1
iPhone 8

Steps to reproduce:
1. Create a profile
2. Enter username and some web reference
3. Go to the settings

Actual result:
The username and link have not been saved
[Recording](https://user-images.githubusercontent.com/13810654/149471202-6421f5ab-47eb-48d1-b739-5c938af97f8c.mov)

**Comment by JeneaVranceanu** [comment]
@arturtkachenko I'll assign you to the github issues that I understand you are working on or already did.

**Comment by JeneaVranceanu** [comment]
Looks like it's the only one, others are already assigned 🙂

**Comment by arturtkachenko** [comment]
> @arturtkachenko I'll assign you to the github issues that I understand you are working on or already did.

Yeah, sorry, forgot to assign it to myself. I'll work on all of them and almost all of them fixed.

**Comment by jnorbert** [comment]
Issue has been fixed.
