### ISSUE TITLE
Probably we should add the lock option similar to the browser extension?

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#35]
Actual result:
<img width="743" alt="Screenshot 2022-01-14 at 09 13 58" src="https://user-images.githubusercontent.com/13810654/149473988-eb49d295-ec34-4a48-80fd-84ef15d46970.png">

Expected result:
<img width="392" alt="Screenshot 2022-01-14 at 09 11 31" src="https://user-images.githubusercontent.com/13810654/149473607-a78fde97-fcc1-4a19-87e0-5019ee1a183b.png">

**Comment by arturtkachenko** [comment]
> I wonder if we want to have this flow 1-1 with extension, after all if we leave the ios app it locks itself automatically correct? @arturtkachenko.

I'm not sure about that, it locks if we go in background mode. So would be nice to have this button for quick lock in mobile app as well.

**Comment by luki3k5** [comment]
@frozeman just want to run it by you quickly - thoughts? I would love to see maximum consistency between ext and mobile app so I would also be suggesting to replace this button with locking. Thanks.

**Comment by frozeman** [comment]
Hm. Why would you lock it without closing the app? To stare at the Lock Screen?
We should lock when closing the app or putting in the bg.

**Comment by luki3k5** [comment]
Banking apps also have this feature - it makes UX more 'safe' mentally for the users imho. They might not know that app auto-locks when they close it or background it.

**Comment by arturtkachenko** [comment]
Alternatively we can replace sensitive info if any with "•••••"

**Comment by frozeman** [comment]
I am not a big fan off manual steps that are technically unnecessary. If you leave the app it locks, if you user knows that or not doesn’t matter, because it safe. 
we want to build things and feel smart, and banking apps never feel smart

**Comment by frozeman** [comment]
For now let’s just lock it every time you leave the app, and request touch ID or face ID when you re-open it. If you want to make more complex path we can do that in the future.
