### ISSUE TITLE
When creating a new profile, the user see the password in the first field that was used to create the first profile

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#40]
Steps to reproduce:
1. Create new profile
2. Create second profile

Actual result:
<img width="724" alt="Screenshot 2022-01-18 at 15 01 46" src="https://user-images.githubusercontent.com/13810654/149951728-021d93fc-62ab-45c6-9a1b-2d026ce6e6b2.png">

**Comment by arturtkachenko** [comment]
Fixed in 0.1 (16) - TestFlight.
