### ISSUE TITLE
After reversal the address should not be upside down

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/universalprofile-ios-app#42]
Actual result:
![IMG_3364](https://user-images.githubusercontent.com/13810654/150142105-41933cf8-2551-452e-bff9-018ee228af41.PNG)

Expected result:
<img width="338" alt="Screenshot 2022-01-19 at 14 42 27" src="https://user-images.githubusercontent.com/13810654/150142283-04bbf31d-e958-443d-b711-b589ecc732ca.png">

**Comment by arturtkachenko** [comment]
@jnorbert we have separate ticket for redesigning profile card.

**Comment by jnorbert** [comment]
Thanks for the info, so I think we can close this issue.
